spring:
  application:
    name: eventbook

  datasource:
    url: jdbc:postgresql://localhost:5432/eventbook
    username: eventbook
    password: eventbook

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.chamith.eventbook: DEBUG
    org:
      springframework:
        web: debug
        http:
          converter:
            json: debug
        security:
          web:
            firewall: debug
